name: Deploy artifacts

on: [push, pull_request]

env:
  MAVEN_REPO_ID: ${{ vars.MAVEN_REPO_ID }}
  MAVEN_REPO_URL: ${{ vars.MAVEN_REPO_URL }}
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Maven authentication
        run: |
            mkdir -p ~/.m2
            cat > ~/.m2/settings.xml <<EOF
            <settings>
              <profiles>
                  <profile>
                    <id>github</id>
                    <activation>
                      <activeByDefault>true</activeByDefault>
                    </activation>
                    <repositories>
                      <repository>
                        <id>central</id>
                        <url>https://repo.maven.apache.org/maven2</url>
                      </repository>
                      <repository>
                        <id>${{ vars.MAVEN_REPO_ID }}</id>
                        <url>${{ vars.MAVEN_REPO_URL }}</url>
                        <snapshots>
                         <enabled>true</enabled>
                        </snapshots>
                        <releases>
                         <enabled>true</enabled>
                        </releases>
                      </repository>
                    </repositories>
                  </profile>
              </profiles>
              <servers>
                <server>
                  <id>${{ vars.MAVEN_REPO_ID }}</id>
                  <username>${{ secrets.MAVEN_USER }}</username>
                  <password>${{ secrets.MAVEN_TOKEN }}</password>
                </server>
              </servers>
            </settings>
            EOF
      - name: Lookup Maven settings
        run: cat ~/.m2/settings.xml
      - name: Deploy Maven artifacts
        run: mvn package
